/**
 * HeatSeaker Template - Commercial Software
 * Copyright (c) 2024 Paul Stortini
 * Software Development & Maintenance by Alexander Meyer
 * 
 * ZERO LIABILITY NOTICE: Service provider assumes no liability for betting operations.
 * Client bears 100% responsibility for all business outcomes.
 * 
 * This software is provided "AS IS" without warranty.
 * For complete terms, see SERVICE_AGREEMENT.md
 * 
 * Tracks Metadata
 * Updated - 2/14/24
 */

const tracks = [
  {
    trackName: 'PLAYGROUND',
    id: '1m7G_5qXIXq7TH3PENAV7c2r0RhLs32NkaYpziwij_rU',
    trackCode: 'PLAY',
    betTrackCode: 'PLAY',
    scriptId: '1Nj4UJR8pGW29ZT1Q2ytMymLHR3VykJqFx-IqJnRTvux4aenR4eiux-wL',
    pickThreeValue: .5,
    winBet: 10,
  },
  {
    trackName: 'SARATOGA',
    id: '1L07Wot8tjXr0EFG5n0NnIIrDyU2MnAvJiGoBFYjujzk',
    trackCode: 'SAR',
    betTrackCode: 'STD',
    scriptId: '1DOvDsq52KFb2akhMJQDh79WfXdJHcilTRYV54ACh6-jswvO59S7DJ_jt',
    pickThreeValue: .5,
    winBet: 10,
  },
  {
    trackName: 'DELMAR',
    id: '12hd-uYem3wMKpzkswh2hZQMaS-0hKyfcXNVaHcRkHDk',
    trackCode: 'DMR',
    trackCode2: 'DMF',
    betTrackCode: 'DMD',
    scriptId: '1oLqi3sv6bfo6gf_2f_QxLCcG8Zrne4NylbpWIrblQLiEdtRVnr6gcgMH',
    pickThreeValue: 2,
    winBet: 10,
  },
  {
    trackName: 'COLONIAL DOWNS',
    id: '1JH9zyoUmHAvxMh7cvJogmUmI_wCscVKSiENDJu27zi0',
    trackCode: 'CNL',
    betTrackCode: 'CNL',
    scriptId: '1mFeirPw_aA00w_gw9OneYqTk0HlNXDOnQlxlK7lDKAkqLcLnbknITVTB',
    pickThreeValue: 2,
    winBet: 10,
    inactive: true
  },
  {
    trackName: 'GULFSTREAM',
    id: '1dYf3zIPhTaehm__-m0IRmJ9mNEbYnrgk5WVSSDOBvGY',
    trackCode: 'GP',
    trackCode2: 'GPW',
    betTrackCode: 'GPM',
    scriptId: '1BO-7Jf5GneJnp4qXG4LSlqV9ywYIui7GeS_M_CkxCT-d_veHZPxOFZ_-',
    pickThreeValue: 2,
    doubleValue: 1,
    winBet: 730,
  },
  {
    trackName: 'MONMOUTH',
    id: '1OtMGuhYFfpOe2_gBGk2GidsSwUdhQOCC_6kWlLeEWc0',
    trackCode: 'MTH',
    betTrackCode: 'MTD',
    scriptId: '1HAPsHRbr-YFcUNUjk800hdCWlwQ4VqWdDvURASQaIGEGQpnUEPge_KPA',
    pickThreeValue: 2,
    winBet: 730,
  },
  {
    trackName: 'ELLIS PARK',
    id: '1lpDCArzoGap3X5K5-7ZAXt3ZTlKDNmSTfZF9IA2XBVM',
    trackCode: 'ELP',
    betTrackCode: 'ELD',
    scriptId: '1Q60sS0DIAD5PYPjO1VeR_AHuARebjvDE3BCUl4z6dl5PIAJ5vDdB7mxj',
    pickThreeValue: 2,
    winBet: 730,
  },
  {
    trackName: 'DELAWARE PARK',
    id: '1ibda3DJEvNU7MMYhVJXTdgrIBJmO7gu4D-uw97Oiq2g',
    trackCode: 'DEL',
    betTrackCode: 'DLD',
    scriptId: '19kTgKGs3ZYiFepgcfu3ZpXTxmMa5FC1zNLeQJ8FbCTpjZTla2PHgdIBJ',
    pickThreeValue: 2,
    winBet: 600,
    inactive: true
  },
  {
    trackName: 'PARX',
    id: '1gCt7QjCDEIDZLIjXDC_T4nHa6skBO-Lv1CzgUeP53ho',
    trackCode: 'PRX',
    betTrackCode: 'PHD',
    scriptId: '1ezIVHzqxH00S9L9vDy3sjiTHzYIakvKdIpLD7RRrqmgbhFOIHO2iQFrf',
    pickThreeValue: .5,
    winBet: 730,
  },
  {
    trackName: 'WOODBINE',
    id: '1a6lLM2B_GhlxKeIpt5T1kuTo5ncKD-LtbW8PakJ42lk',
    trackCode: 'WO',
    betTrackCode: 'WOT',
    scriptId: '1utgxfZ52A_STyBY2FFX_xMDJXmlGw7V-OVeya7NEzHjzqoLFtOqaqldc',
    pickThreeValue: 5,
    winBet: 730,
  },
  {
    trackName: 'CHURCHILL',
    id: '1b0h7hlVbrwrU_Z8ruyKjtMAEVXOaKeBJlHe-ipgRx4c',
    trackCode: 'CD',
    betTrackCode: 'CHD',
    scriptId: '1Gntk8wgp7uhTQPFsjU32Gj_GmS83NPPE-Wd66zjVdeStgWSIklQMJZ8i',
    pickThreeValue: 2,
    winBet: 730,
  },
  {
    trackName: 'BELMONT',
    id: '1BeVpd2RC_5LEhd7njWHNMvAJE-Vq7b3ASeF7CLbofoA',
    trackCode: 'BEL',
    betTrackCode: 'BED',
    scriptId: '1GsvLdDLwSgI7_V0d3zY554f9VSD_quZ2bR_K_xSaIcTs8p18JgibQVAk',
    pickThreeValue: .5,
    winBet: 730,
  },
  {
    trackName: 'KEENELAND',
    id: '1JRbhS3J5S_5EzLBw1Ll_VObFxITQQ1y-y0PzPE5A9_Y',
    trackCode: 'KEE',
    betTrackCode: 'KED',
    scriptId: '1WSMu2UbK2kwEiHAwY9B0WMS1Zc4v2shymfSJyBm3HgMwhaoljLEV9Zde',
    pickThreeValue: 2,
    winBet: 600,
  },
  {
    trackName: 'SANTA ANITA',
    id: '1Gq3-DLWLF3PqLwHmUH4HDdcSlVFR5LGRNF5Z5VbTvhQ',
    trackCode: 'SA',
    betTrackCode: 'SAD',
    scriptId: '1w4Jed9DQdOsjFzq2W5HADiQmpJRGYz-W-etlxG_LAt7w6EnB9k2tTrBm',
    pickThreeValue: 2,
    doubleValue: 1,
    winBet: 730,
  },
  {
    trackName: 'LOS ALAMITOS',
    id: '13yp7NQMQq_K1TLMYkqz30i9F7864085-xT4urfFpSeQ',
    trackCode: 'LA',
    betTrackCode: 'LQD',
    scriptId: '1UEFnHmbZnTxNR0B5LZPfzjUkpkVsFi9fE9s_2dt3mH0HEk6eD9f84gQ2',
    pickThreeValue: .5,
    winBet: 10,
    inactive: true
  },
  {
    trackName: 'LAUREL',
    id: '1kEZTybiQlsn_XhPDO8ZodmUK6e8O5Uisc9OvvbTxQvQ',
    trackCode: 'LRL',
    betTrackCode: 'LRM',
    scriptId: '15x7YoRLA9L6c9Xm0i5CTPLEOHHnklJazTZmBf4bAwAufwifyzxqW2pbz',
    pickThreeValue: 2,
    winBet: 600,
  },
  {
    trackName: 'PIMLICO',
    id: '1DGioZT3qVSrLoCi1NvugR4x3IzrGzU1vbwBngTwBvOE',
    trackCode: 'PIM',
    betTrackCode: 'PIM',
    scriptId: '1ZO3actElO4N1aW277rYSTUEUa7pAsnyAzd3eV0KakGijchCIVSnvH7O5',
    pickThreeValue: 2,
    winBet: 730,
  },
  {
    trackName: 'KENTUCKY DOWNS',
    id: '1QLOJ3L67F4qB5ZR9IRuL5JuBBaTKdxXhrWXg0yEhwlg',
    trackCode: 'KD',
    betTrackCode: 'KDM',
    scriptId: '1tkkSap2XTD7xzPuxn6xMDvSE88LbvX4HCEZ6k2WcPvsQLHZPdlvaoUnn',
    pickThreeValue: 2,
    winBet: 10,
  },
  {
    trackName: 'CANTERBURY PARK',
    id: '1yDtTKDpFFGDap4-xgjcqJxlx6Sd92JTZ6m9wu1IPev8',
    trackCode: 'CBY',
    betTrackCode: 'CBD',
    scriptId: '1zzEFsy-Gp0yluSorGjeDROAC6PmUTMuijdq1hXHOzXG8EWRRVSOgCIuF',
    pickThreeValue: 2,
    winBet: 10,
    inactive: true
  },
  {
    trackName: 'GOLDEN GATE',
    id: '1FOIf6UcRbsEbqslApqiPG6OZIwh6rHDY_X5cV_vC6Hc',
    trackCode: 'GG',
    betTrackCode: 'GGD',
    scriptId: '1pxOnnlTs-AFeAgD1DC9YyYMVIWyhiDDbwVWW-1faoNn6l88MNPCPBw35',
    pickThreeValue: 2,
    winBet: 730,
    inactive: true
  },
  {
    trackName: 'PENN NATIONAL',
    id: '1By2zoE60RBR-WRbb7lBJIub9FnouMov8U-v-ACkjeAQ',
    trackCode: 'PEN',
    betTrackCode: 'PEN',
    scriptId: '1zD8zfqfVSGvrKoQGhEXO4y-XPnJiVQYjwvR9WpYYBFRHG1XRY0qXTDl8',
    pickThreeValue: 2,
    winBet: 600,
    inactive: true
  },
  {
    trackName: 'BEYER AVERAGES',
    id: '1qMcEzEQFE4yerbAyiQnWhs29Ox6SuhbNFQBYeuwcKlQ',
    trackCode: 'BAC',
    betTrackCode: '',
    scriptId: '1cnxnopNYq5LgQxK14ZKlpt4qfL9UdPKeI9B353iZyY4l3Z_GImdjQpDw',
    pickThreeValue: 2,
    winBet: 10,
  },
  {
    trackName: 'AQUEDUCT',
    id: '1yORyqZThXoyxlpoAWwLEaf7dnMK-XLay6p7MNhpFL6U',
    trackCode: 'AQU',
    betTrackCode: 'AQD',
    scriptId: '1Sy_-6Lb9VS7LNDxrGQCfacuGzng5qtNAyi5un6eM6nRvVSWpTxZaXq6F',
    pickThreeValue: 1,
    doubleValue: 1,
    winBet: 600,
  },
  {
    trackName: 'TAMPA BAY',
    id: '1n13ru7JXpGkyIyKtU6f6f7xkVhzfmV_2Er39E03FMLo',
    trackCode: 'TAM',
    betTrackCode: 'TAM',
    scriptId: '1yg6ZfhrPDKCT-EhIR_oFO9P9BCrv5qnBKCpc_9eJtk8er0mgsDkYY0qc',
    pickThreeValue: 2,
    winBet: 600,
  },
  {
    trackName: 'OAKLAWN',
    id: '1JM40Q1pLZiv0uceLb_20vP52szUHPkSDw473q3Sty4c',
    trackCode: 'OP',
    betTrackCode: 'OPM',
    scriptId: '1xM_H4_KRteBMFL7TR17dW_U7y6wO508nUFTAHSSZiKOspemP2ANHpmOR',
    pickThreeValue: 2,
    doubleValue: 1,
    winBet: 10,
  },
  {
    trackName: 'WOODBINE HARNESS',
    id: '1O2I0QRJdOsK9Ied4Wr3eZ626w4x2f8u3NRsDNbQxDAM',
    trackCode: 'WOH',
    betTrackCode: 'WOH',
    scriptId: '1U14cq3MWs_RjoqpWJ540OCDl5AI08kMwBSV9XgKSk_FohVax5auL3UuE',
    pickThreeValue: 5,
    winBet: 730,
    inactive: true
  },
]
